apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    description: "This is a sample service for MyApp."
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
  links:
    - name: db
      target: my-db
  annotations:
    db-version: "1.2.3"
